### ISSUE TITLE
setup database

### ISSUE THREAD

**Issue by jessicasalmon** [FAC10/fac-donation-app#20]
- [x] setup connection pool
- [x] build db file 
- [x] build tables 
- [x] host on heroku

**Comment by jessicasalmon** [comment]
database will hold two tables: **users** and **payments** 

see #44

**Comment by joeylouise** [comment]
To create database on Heroku
* Login to Heroku via CLI (type `heroku` in command line)
* Then type:
`heroku addons:create heroku-postgresql:hobby-dev --app fac-donation-app`

This will create a DATABASE_URL in Heroku config.vars, which you then add to your config.env file

[How to set up Heroku database](https://github.com/pbywater/week7-PAJeS/blob/master/Learnings.md)
